[package]
name = "live_map_be"
version = "0.1.0"
authors = ["njanke96 <nathanjanke96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "0.6.1"
